<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.NET.Test.SDK" Version="18.3.0" />
    <PackageReference Include="NUnit" Version="4.5.0" />
	  <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SalesTaxCalculator\SalesTaxCalculator.csproj" />
  </ItemGroup>

</Project>
